/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#e2e7ff',
        'outline-variant': '#c2c6d1',
        'on-error-container': '#93000a',
        'tertiary-container': '#004d79',
        'surface-variant': '#dae2fd',
        'secondary-fixed-dim': '#ffb1c2',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001c38',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#eef0ff',
        'on-surface-variant': '#424750',
        'surface-tint': '#27609d',
        'tertiary-fixed': '#cee5ff',
        error: '#ba1a1a',
        'inverse-surface': '#283044',
        'on-primary-container': '#8abcff',
        'surface-dim': '#d2d9f4',
        'on-secondary-container': '#fffbff',
        'on-tertiary-fixed': '#001d32',
        'secondary-container': '#e0186b',
        primary: '#003461',
        'on-tertiary-container': '#76bfff',
        background: '#faf8ff',
        'on-primary-fixed-variant': '#004882',
        surface: '#faf8ff',
        'on-secondary-fixed': '#3f0018',
        'surface-container': '#eaedff',
        'primary-fixed-dim': '#a3c9ff',
        'secondary-fixed': '#ffd9e0',
        'primary-fixed': '#d3e4ff',
        'on-surface': '#131b2e',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#faf8ff',
        'surface-container-highest': '#dae2fd',
        'error-container': '#ffdad6',
        'inverse-primary': '#a3c9ff',
        'primary-container': '#004b87',
        'on-secondary-fixed-variant': '#8f0040',
        'on-background': '#131b2e',
        secondary: '#b70054',
        'tertiary-fixed-dim': '#96ccff',
        tertiary: '#003656',
        outline: '#727781',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'on-tertiary-fixed-variant': '#004a75',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '2rem',
        'space-lg': '1.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'gutter-mobile': '1rem',
        'margin-mobile': '1rem',
        'space-xl': '2.5rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        'title-lg': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        'title-md': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'headline-xl': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        caption: ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '56px', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        caption: ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', fontWeight: '800' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
